// const { Image } = require("react-native");

const product = [
    {
      id: '1',
      name: 'Ballerinas assumenda soluta iusto nostrum odio',
      image: require('../../assets/product-1.png'),
      description: 'Lorem ipum dolor sit ammet. Dummy Text',
      price: 1115,
      countInStock: 57,
      rating: 3,
      numOfReviews: 256,
    },
    {
      id: '2',
      name: 'Velcro Ballerinas',
      image: require('../../assets/product-2.png'),
      description: 'Lorem ipum dolor sit ammet. Dummy Text',
      price: 783,
      countInStock: 84,
      rating: 4.1,
      numOfReviews: 81,
    },
    {
      id: '3',
      name: 'Neque assumenda soluta iusto nostrum odio',
      image: require('../../assets/product-3.png'),
      description: 'Lorem ipum dolor sit ammet. Dummy Text',
      price: 423,
      countInStock: 37,
      rating: 3.2,
      numOfReviews: 302,
    },
    {
      id: '4',
      name: 'Soluta iusto nostrum odio Velcro Ballerinas',
      image: require('../../assets/product-4.png'),
      description: 'Lorem ipum dolor sit ammet. Dummy Text',
      price: 583,
      countInStock: 99,
      rating: 3.7,
      numOfReviews: 106,
    },
    {
      id: '5',
      name: 'Odio Neque assumenda soluta iusto nostrum odio',
      image: require('../../assets/product-5.png'),
      description: 'Lorem ipum dolor sit ammet. Dummy Text',
      price: 243,
      countInStock: 22,
      rating: 4.5,
      numOfReviews: 41,
    },
    {
      id: '6',
      name: 'Neque assumenda soluta iusto nostrum odio elcro Ballerinas',
      image: require('../../assets/product-6.png'),
      description: 'Lorem ipum dolor sit ammet. Dummy Text',
      price: 933,
      countInStock: 113,
      rating: 4.6,
      numOfReviews: 49,
    },
    {
      id: '7',
      name: 'Velcro Ballerinas Neque assumenda soluta',
      image: require('../../assets/product-7.png'),
      description: 'Lorem ipum dolor sit ammet. Dummy Text',
      price: 1383,
      countInStock: 93,
      rating: 3.8,
      numOfReviews: 223,
    },
    {
      id: '8',
      name: 'Velcro Ballerinas',
      image: require('../../assets/product-8.png'),
      description: 'Lorem ipum dolor sit ammet. Dummy Text',
      price: 1493,
      countInStock: 33,
      rating: 4.1,
      numOfReviews: 142,
    },
    {
      id: '9',
      name: 'Ballerinas Neque assumenda soluta iusto nostrum odio',
      image: require('../../assets/product-9.png'),
      description: 'Lorem ipum dolor sit ammet. Dummy Text',
      price: 553,
      countInStock: 3,
      rating: 4.5,
      numOfReviews: 74,
    },
    {
      id: '10',
      name: 'Assumenda soluta iusto nostrum odio',
      image: require('../../assets/product-10.png'),
      description: 'Lorem ipum dolor sit ammet. Dummy Text',
      price: 373,
      countInStock: 75,
      rating: 3.4,
      numOfReviews: 332,
    },
    {
      id: '11',
      name: 'Velcro Neque assumenda soluta iusto nostrum odio Ballerinas',
      image: require('../../assets/product-11.png'),
      description: 'Lorem ipum dolor sit ammet. Dummy Text',
      price: 515,
      countInStock: 13,
      rating: 3.6,
      numOfReviews: 421,
    },
    {
      id: '12',
      name: 'Iusto nostrum odio neque assumenda soluta iusto nostrum odio',
      image: require('../../assets/product-12.png'),
      description: 'Lorem ipum dolor sit ammet. Dummy Text',
      price: 483,
      countInStock: 31,
      rating: 4.6,
      numOfReviews: 91,
    },
  ];
  
  // const products = [
  //     {
  //         _id: "1",
  //         name: 'Image 1',
  //         image: require('../../assets/aditya-aiyar.png')
  
  //     }
  // ]
  
  export default product;